networks: 
        sym-ai:
                driver: bridge

services:
        ef:
                image: extract_features
                container_name: ef
                ports:
                        - 5000:5000
                networks:
                        - sym-ai
                build:
                        context: ./extract_features
                        dockerfile: ./Dockerfile
        preprocessing:
                image: preprocessing
                container_name: preprocessing
                ports:
                        - 5001:5000
                networks:
                        - sym-ai
                build:
                        context: ./preprocessing
                        dockerfile: ./Dockerfile
