networks: 
        sym-ai:
                driver: bridge
        rtmp_rtmp:
                external: true

services:
        common:
                image: aits-common
                build:
                        context: ./common
                        dockerfile: ./Dockerfile
                command: echo "Done"
        ef:
                depends_on: 
                        - common
                image: extract_features
                networks:
                        - sym-ai
                build:
                        context: ./extract_features
                        dockerfile: ./Dockerfile
                deploy:
                        mode: replicated
                        replicas: 20
                        endpoint_mode: vip
                        resources:
                                limits:
                                        cpus: '13.00'
                                        memory: 13G
                                reservations:
                                        cpus: '1.00'
                                        memory: 500M
        preprocessing:
                depends_on: 
                        - common
                image: preprocessing
                #container_name: preprocessing
                #ports:
                #        - 127.0.0.1:5001:5000
                networks:
                        - sym-ai
                build:
                        context: ./preprocessing
                        dockerfile: ./Dockerfile
                deploy:
                        mode: replicated
                        replicas: 3
                        endpoint_mode: vip
                        resources:
                                limits:
                                        cpus: '3.00'
                                        memory: 3G
                                reservations:
                                        cpus: '1.00'
                                        memory: 1G
        htk_train:
                depends_on: 
                        - common
                image: htk_train
                #container_name: htk_train
                # ports:
                #        - 127.0.0.1:5020:5000
                networks:
                        - sym-ai
                build:
                        context: ./htk_train
                        dockerfile: ./Dockerfile
                volumes: 
                        - type: bind
                          source: ./shared
                          target: /shared
                          read_only: true
                deploy: 
                        mode: replicated
                        replicas: 10
                        endpoint_mode: vip
                        resources:
                                limits:
                                        cpus: '10.00'
                                        memory: 10G
                                reservations:
                                        cpus: '10.00'
                                        memory: 10G
        htk_test:
                depends_on: 
                        - common
                image: htk_test
                #container_name: htk_test
                # ports:
                #        - 127.0.0.1:5020:5000
                networks:
                        - sym-ai
                build:
                        context: ./htk_test
                        dockerfile: ./Dockerfile
                volumes: 
                        - type: bind
                          source: ./shared
                          target: /shared
                          read_only: true
                deploy: 
                        mode: replicated
                        replicas: 10
                        endpoint_mode: vip
                        resources:
                                limits:
                                        cpus: '10.00'
                                        memory: 10G
                                reservations:
                                        cpus: '10.00'
                                        memory: 10G
        hsv_train:
                depends_on: 
                        - common
                image: hsv_train
                container_name: hsv_train
                ports:
                        - 127.0.0.1:5003:5000
                networks:
                        - sym-ai
                build:
                        context: ./hsv_train
                        dockerfile: ./Dockerfile
                volumes: 
                        - type: bind
                          source: ./shared
                          target: /shared
                          read_only: true
                        - type: bind
                          source: ./shared/viz
                          target: /viz

        hsv_test:
                depends_on: 
                        - common
                image: hsv_test
                container_name: hsv_test
                ports:
                        - 127.0.0.1:5004:5000
                networks:
                        - sym-ai
                build:
                        context: ./hsv_test
                        dockerfile: ./Dockerfile
                volumes: 
                        - type: bind
                          source: ./shared
                          target: /shared
                          read_only: true

        hsv_train_iterative:
                depends_on: 
                        - common
                image: hsv_train_iterative
                container_name: hsv_train_iterative
                ports:
                        - 127.0.0.1:5005:5000
                networks:
                        - sym-ai
                build:
                        context: ./hsv_train_iterative
                        dockerfile: ./Dockerfile
                volumes: 
                        - type: bind
                          source: ./shared
                          target: /shared
                          read_only: true
                        - type: bind
                          source: ./shared/viz
                          target: /viz

        ui:
                depends_on: 
                        - common
                image: aits-ui
                container_name: aits-ui
                build:
                        context: ./ui
                        dockerfile: ./Dockerfile
                ports:
                        - 11225:5000
                networks:
                        - sym-ai
                volumes: 
                        - type: bind
                          source: ./shared
                          target: /shared
                        - type: bind
                          source: ./shared/viz
                          target: /app/static

        main:
                depends_on: 
                        - common
                image: aits-main
                container_name: aits-main
                build:
                        context: ./main
                        dockerfile: ./Dockerfile
                networks:
                        - sym-ai
                        - rtmp_rtmp
                volumes: 
                        - type: bind
                          source: ./shared
                          target: /shared
                          #        main_other:
                          #                image: aits-main_other
                          #                container_name: aits-main_other
                          #                build:
                          #                        context: ./main_other
                          #                        dockerfile: ./Dockerfile
                          #                networks:
                          #                        - sym-ai
                          #                        - rtmp_rtmp
                          #                volumes: 
                          #                        - type: bind
                          #                          source: ./shared
                          #                          target: /shared
