networks: 
        sym-ai:
                driver: bridge

services:
        ef:
                image: extract_features
                container_name: ef
                ports:
                        - 5000:5000
                networks:
                        - sym-ai
                build:
                        context: ./extract_features
                        dockerfile: ./Dockerfile
        preprocessing:
                image: preprocessing
                container_name: preprocessing
                ports:
                        - 5001:5000
                networks:
                        - sym-ai
                build:
                        context: ./preprocessing
                        dockerfile: ./Dockerfile
        
        htk:
                image: htk
                container_name: htk
                ports:
                        - 5002:5000
                networks:
                        - sym-ai
                build:
                        context: ./n_folds
                        dockerfile: ./Dockerfile
                volumes: 
                        - ./tmp/input/data:/app/symbiosis/all-data
                        - ./tmp/input/label:/app/symbiosis/all-labels
                        - ./tmp/output/data:/app/symbiosis/data
                        - ./tmp/output/results:/app/symbiosis/results
                        - ./tmp/model/mlf:/app/symbiosis/mlf
                        - ./tmp/model/models:/app/symbiosis/models
