owner: calix # fill in your name here
file_paths:
  video_file_path: "/home/calix/Desktop/aits/videos" # directory containing videos
  htk_input_file_path: "/home/calix/Desktop/aits/ai-through-symbiosis" # directory containing htk input vectors
  label_file_path: "/home/calix/Desktop/aits/ai-through-symbiosis/Labels" # directory containing pick labels (order of labels, i.e. r1b1...)
  htk_output_file_path: "/home/calix/Desktop/aits/ai-through-symbiosis" # directort containing results from HTK (i.e. HTK output folder)
  elan_annotated_file_path: "/home/calix/Desktop/aits/ai-through-symbiosis/elan_annotated" # directory containing ELAN annotated labels for videos