owner: darhsan # fill in your name here
file_paths:
  video_file_path: "/home/darshan/ai-through-symbiosis/scripts/data/Videos" # directory containing videos
  htk_input_file_path: "/home/darshan/ai-through-symbiosis/htk_inputs/picklist136to234_280bins" # directory containing htk input vectors
  label_file_path: "/home/darshan/ai-through-symbiosis/htk_inputs/label" # directory containing pick labels (order of labels, i.e. r1b1...)
  # training
  # htk_output_file_path: "C:/Users/chngz/OneDrive/Georgia Tech/AI Through Symbiosis/pick_list_dataset/htk_outputs/icassp_train_folds/avgFold" # directory containing results from HTK (i.e. HTK output folder)
  # testing, picklists 1-90
  htk_output_file_path: "/home/darshan/ai-through-symbiosis/htk_outputs/icassp_train_folds/avgFold"
  elan_annotated_file_path: "/home/darshan/ai-through-symbiosis/elan_annotated" # directory containing ELAN annotated labels for videos