owner: ming # fill in your name here
file_paths:
  video_file_path: "C:/Users/chngz/OneDrive/Georgia Tech/AI Through Symbiosis/pick_list_dataset/Videos" # directory containing videos
  # train picklist 136 to 234
  # htk_input_file_path: "C:/Users/chngz/OneDrive/Georgia Tech/AI Through Symbiosis/pick_list_dataset/htk_inputs/picklist136to234_280bins" # directory containing htk input vectors
  # test picklist 41 to 90
  htk_input_file_path: "C:/Users/chngz/OneDrive/Georgia Tech/AI Through Symbiosis/pick_list_dataset/htk_inputs" # directory containing htk input vectors
  label_file_path: "C:/Users/chngz/OneDrive/Georgia Tech/AI Through Symbiosis/pick_list_dataset/Labels" # directory containing pick labels (order of labels, i.e. r1b1...)
  # training
#  htk_output_file_path: "C:/Users/chngz/OneDrive/Georgia Tech/AI Through Symbiosis/pick_list_dataset/htk_outputs/icassp_train_folds/avgFold" # directory containing results from HTK (i.e. HTK output folder)
  # testing, picklists 1-90
  htk_output_file_path: "C:/Users/chngz/OneDrive/Georgia Tech/AI Through Symbiosis/pick_list_dataset/htk_outputs/ood-1-90-results/ood-1-90-results"
  elan_annotated_file_path: "C:/Users/chngz/Documents/AI through Symbiosis/HandGestureRecognition/elan_annotated" # directory containing ELAN annotated labels for videos
